config/routes.rb
Rails.application.routes.draw do
	get 'admin/account_preferences', to: 'page#account_preferences'
	get 'admin/account_notifications', to: 'page#account_notifications'
	get 'admin/account_payouts', to: 'page#account_payouts'
	get 'admin/account_payment_methods', to: 'page#account_payment_methods'
	get 'admin/contact', to: 'page#contact'
	get 'admin/terms', to: 'page#terms'
	get 'admin/privacy_policy', to: 'page#privacy_policy'
	get 'admin/api', to: 'page#api'
	get 'admin/changelog', to: 'page#changelog'
	get 'admin/help_center', to: 'page#help_center'
	get 'admin/edit_booking', to: 'page#edit_booking'
	get 'admin/booking', to: 'page#booking'
	get 'admin/new_booking', to: 'page#new_booking'
	get 'admin/bookings', to: 'page#bookings'
	get 'admin/insights', to: 'page#insights'
	get 'admin/calendar', to: 'page#calendar'
	get 'admin/inbox', to: 'page#inbox'
	get 'admin/properties', to: 'page#properties'

	get 'dashboard', to: 'dashboard#index'
	get 'pricing', to: 'page#pricing'
	get '', to: 'page#landing'



  if Rails.env.development? || Rails.env.test?
    mount Railsui::Engine, at: "/railsui"
  end

  # Inherits from Railsui::PageController#index
  # To overide, add your own page#index view or change to a new root
  # Visit the start page for Rails UI any time at /railsui/start
  root action: :index, controller: "railsui/page"

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_person_name
  has_one_attached :avatar


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper Railsui::ThemeHelper

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :name])
  end

  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index
		render layout: 'admin'
	end
end

app/controllers/generes_controller.rb
class GeneresController < ApplicationController
end

app/controllers/page_controller.rb
class PageController < ApplicationController

	def account_preferences
		render layout: 'admin'
	end

	def account_notifications
		render layout: 'admin'
	end

	def account_payouts
		render layout: 'admin'
	end

	def account_payment_methods
		render layout: 'admin'
	end

	def contact
		render layout: 'admin'
	end

	def terms
		render layout: 'admin'
	end

	def privacy_policy
		render layout: 'admin'
	end

	def api
		render layout: 'admin'
	end

	def changelog
		render layout: 'admin'
	end

	def help_center
		render layout: 'admin'
	end

	def edit_booking
		render layout: 'admin'
	end

	def booking
		render layout: 'admin'
	end

	def new_booking
		render layout: 'admin'
	end

	def bookings
		render layout: 'admin'
	end

	def insights
		render layout: 'admin'
	end

	def calendar
		render layout: 'admin'
	end

	def inbox
		render layout: 'admin'
	end

	def properties
		render layout: 'admin'
	end

	def pricing
	end

	def about
	end


	def landing
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
end

app/controllers/readlists_controller.rb
class ReadlistsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/generes_helper.rb
module GeneresHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/readlists_helper.rb
module ReadlistsHelper
end

app/views/dashboard/index.html.erb
<div class="relative min-h-[320px] md:py-16 py-14 border-b border-zinc-200 dark:border-zinc-700/80">
  <div class="opacity-5 blur-4xl absolute inset-0 w-full h-full
    bg-gradient-to-r from-white via-primary-500/40 via-[24.79%] to-[#177BB5] z-0"></div>

    <% current_hour = Time.now.hour %>
    <% greeting = case current_hour
                when 0..11
                  "Good morning"
                when 12..17
                  "Good afternoon"
                else
                  "Good evening"
                end %>

  <div class="relative z-20">
    <% if user_signed_in? %>
      <h2 class="text-4xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight text-center"><%= "#{greeting}, #{current_user.first_name}" %></h2>
    <% else %>
      <h2 class="text-4xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight text-center"><%= "#{greeting}" %></h2>
    <% end %>
    <p class="font-light font-heading text-center py-4 text-zinc-700 dark:text-zinc-300">Here is what's happening today
    </p>

    <div class="grid md:grid-cols-4 grid-cols-2 px-4 md:gap-6 gap-3 md:pt-6 pt-3 max-w-5xl mx-auto">
      <%= link_to (defined?(admin_inbox_path) ? admin_inbox_path : "#"), class: "bg-white border border-zinc-300 p-4 rounded-lg shadow-sm hover:shadow-none focus:ring-4 focus:ring-zinc-100/70 md:col-span-1 col-span-2 dark:bg-zinc-800/90 dark:border-zinc-600/80 dark:focus:ring-zinc-600/30 dark:focus:border-zinc-600" do %>
        <h3 class="font-normal text-base font-sans text-zinc-800/80 dark:text-zinc-300">Inbox</h3>
        <p class="font-heading text-4xl font-semibold text-zinc-800 dark:text-white">39</p>
      <% end %>

      <%= link_to "#", class: "bg-white border border-zinc-300 p-4 rounded-lg shadow-sm hover:shadow-none focus:ring-4 focus:ring-zinc-100/70 md:col-span-1 col-span-2 dark:bg-zinc-800/90 dark:border-zinc-600/80 dark:focus:border-zinc-600 dark:focus:ring-zinc-600/30" do %>
        <h3 class="font-normal text-base font-sans text-zinc-800/80 dark:text-zinc-300">Sched. messages</h3>
        <p class="font-heading text-4xl font-semibold text-zinc-800 dark:text-white">46</p>
      <% end %>

      <%= link_to "#", class: "bg-white border border-zinc-300 p-4 rounded-lg shadow-sm hover:shadow-none focus:ring-4 focus:ring-zinc-100/70 md:col-span-1 col-span-2 dark:bg-zinc-800/90 dark:border-zinc-600/80 dark:focus:border-zinc-600 dark:focus:ring-zinc-600/30" do %>
        <h3 class="font-normal text-base font-sans text-zinc-800/80 dark:text-zinc-300">Arrivals</h3>
        <p class="font-heading text-4xl font-semibold text-zinc-800 dark:text-white">2</p>
      <% end %>

      <%= link_to "#", class: "bg-white border border-zinc-300 p-4 rounded-lg shadow-sm hover:shadow-none focus:ring-4 focus:ring-zinc-100/70 md:col-span-1 col-span-2 dark:bg-zinc-800/90 dark:border-zinc-600/80 dark:focus:border-zinc-600 dark:focus:ring-zinc-600/30" do %>
        <h3 class="font-normal text-base font-sans text-zinc-800/80 dark:text-zinc-300">Departures</h3>
        <p class="font-heading text-4xl font-semibold text-zinc-800 dark:text-white">1</p>
      <% end %>
    </div>
  </div>
</div>

<div class="container mx-auto px-4 pt-16">
  <div class="flex md:justify-between justify-center items-center flex-wrap">
    <div class="flex items-center space-x-3 flex-1 md:mb-0 mb-3">
      <button type="button" class="btn btn-primary">Arrivals (2)</button>
      <button type="button" class="btn btn-white">Departures (1)</button>
    </div>

    <%= link_to "View all bookings", (defined?(admin_bookings_path) ? admin_bookings_path : "#"), class: "btn btn-link" %>
  </div>

  <div class="grid xl:grid-cols-4 lg:grid-cols-3 md:grid-cols-2 grid-cols-1 gap-6 my-8">

    <!-- Property user card 1 -->
    <div class="border border-zinc-300/90 shadow-sm shadow-zinc-300/20 rounded-lg p-3 dark:shadow-zinc-950/50 dark:bg-zinc-800/90 dark:border-zinc-600/80 dark:focus:ring-zinc-600/30 dark:focus:border-zinc-600">
      <%= image_tag "property-1.jpg", alt: "Image of Alpine Retreat Haven", class: "rounded-lg h-[174px] w-full object-cover object-center shadow dark:shadow-none dark:border dark:border-zinc-600/80 border-transparent" %>
      <div class="flex items-center space-x-3 mt-4">
        <%= image_tag demo_avatar_url(variant: "men", id: "88"), class: "w-10 h-10 rounded-full object-cover", alt: "Noah Martinez" %>
        <div class="flex-1">
          <p class="font-medium dark:text-white font-heading text-zinc-900">Noah Martinez</p>
          <p class="font-light text-sm text-zinc-600 font-heading dark:text-zinc-400">Alpine Retreat Haven</p>
        </div>
      </div>
      <div class="flex justify-between items-end pt-3">
        <div class="flex items-center space-x-2">
          <%= icon "clock", classes: "w-5 h-5 text-zinc-500 stroke-current dark:text-zinc-300" %>
          <span class="text-zinc-600 dark:text-zinc-400 text-sm">Aug 24, 3pm</span>
        </div>
        <%= link_to "View", (defined?(admin_booking_path) ? admin_booking_path : "#"), class: "btn btn-white" %>
      </div>
    </div>

    <!-- Property user card 2 -->
    <div class="border border-zinc-300/90 shadow-sm shadow-zinc-300/20 rounded-lg p-3 dark:shadow-zinc-950/50 dark:bg-zinc-800/90 dark:border-zinc-600/80 dark:focus:ring-zinc-600/30 dark:focus:border-zinc-600">
      <%= image_tag "property-3.jpg", alt: "Image of Mountain Vista Chalet", class: "rounded-lg h-[174px] w-full object-cover object-center shadow dark:shadow-none dark:border dark:border-zinc-600/80 border-transparent" %>
      <div class="flex items-center space-x-3 mt-4">
        <%= image_tag demo_avatar_url(variant: "women", id: "78"), class: "w-10 h-10 rounded-full object-cover", alt: "Dannie White" %>
        <div class="flex-1">
          <p class="font-medium dark:text-white font-heading text-zinc-900">Dannie White</p>
          <p class="font-light text-sm text-zinc-600 font-heading dark:text-zinc-400">Mountain Vista Chalet</p>
        </div>
      </div>
      <div class="flex justify-between items-end pt-3">
        <div class="flex items-center space-x-2">
          <%= icon "clock", classes: "w-5 h-5 text-zinc-500 stroke-current dark:text-zinc-300" %>
          <span class="text-zinc-600 dark:text-zinc-400 text-sm">Aug 24, 3pm</span>
        </div>
        <%= link_to "View", (defined?(admin_booking_path) ? admin_booking_path : "#"), class: "btn btn-white" %>
      </div>
    </div>
  </div>
</div>

<div class="container mx-auto px-4 pt-16">
  <div class="md:flex items-center justify-between">
    <div class="md:flex-1">
      <h3 class="text-3xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight mb-3">Recent stats</h3>
      <p class="text-zinc-500 font-sans dark:text-zinc-300">Past 30 days</p>
    </div>
    <form action="#" class="md:min-w-[250px] md:w-auto w-full md:mt-0 mt-4">
      <select name="recent_states_properties" class="form-select">
        <option value="">Select property</option>
        <option value="Alpine Retreat Haven">Alpine Retreat Haven</option>
        <option value="Mount Vista Chalet">Mountain Vista Chalet</option>
        <option value="Cozy Mountain A-Frame">Cozy Mountain A-Frame</option>
      </select>
    </form>
  </div>

  <div class="grid grid-cols-2 md:grid-cols-5 gap-6 md:divide-x divide-x-0 mt-6 dark:divide-zinc-700">
    <div class="md:pr-6 md:py-3">
      <p class="text-zinc-600 mb-1 dark:text-zinc-200">Clicks</p>
      <h4 class="text-4xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight">243</h4>
    </div>
    <div class="md:px-6 md:py-3">
      <p class="text-zinc-600 mb-1 dark:text-zinc-200">Impressions</p>
      <h4 class="text-4xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight">1231</h4>
    </div>
    <div class="md:px-6 md:py-3">
      <p class="text-zinc-600 mb-1 dark:text-zinc-200">Conversion rate</p>
      <h4 class="text-4xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight">2.2<sup class="text-xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight pl-1">%</sup></h4>
    </div>
    <div class="md:px-6 md:py-3">
      <p class="text-zinc-600 mb-1 dark:text-zinc-200">Bookings</p>
      <h4 class="text-4xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight">16</h4>
    </div>
    <div class="md:pl-4 md:py-3">
      <p class="text-zinc-600 mb-1 dark:text-zinc-200">Response time</p>
      <h4 class="text-4xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight">~1<sup class="text-xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight pl-1">hr</sup></h4>
    </div>
  </div>
</div>

<div class="container mx-auto px-4 py-24">
  <h3 class="mb-6 font-semibold text-zinc-700 dark:text-zinc-50">Resources</h3>

  <div class="grid lg:grid-cols-4 md:grid-cols-2 grid-cols-1 lg:gap-6 md:gap-4 gap-4">
    <%= link_to (defined?(admin_contact_path) ? admin_contact_path : "#"), class: "border border-zinc-300/80 shadow-sm shadow-zinc-300/25 hover:shadow flex items-center rounded-lg px-4 py-5 space-x-3 focus:ring-4 focus:ring-zinc-100/80 group transition ease-in-out duration-200 dark:bg-zinc-800/90 dark:border-zinc-600/80 dark:focus:ring-zinc-600/30 dark:focus:border-zinc-600 dark:shadow-zinc-950/30" do %>
      <div class="w-10 h-10 rounded-full border border-primary-300/80 flex items-center justify-center bg-white flex-shrink-0 transition ease-in-out duration-200 group-hover:bg-primary-50/50 dark:bg-zinc-800/90 dark:group-hover:bg-primary-600/20 dark:border-primary-600/80">
        <%= icon "lifebuoy", classes: "w-6 h-6 text-primary-600 flex-shrink-0" %>
      </div>
      <div>
        <h5 class="text-base font-medium font-heading text-zinc-700 dark:text-zinc-100 tracking-tight">Get support</h5>
        <p class="text-sm text-zinc-500 dark:text-zinc-400">Contact our support team chat.</p>
      </div>
    <% end %>

    <%= link_to (defined?(admin_help_center_path) ? admin_help_center_path : "#"), class: "border border-zinc-300/80 shadow-sm shadow-zinc-300/25 hover:shadow flex items-center rounded-lg px-4 py-5 space-x-3 focus:ring-4 focus:ring-zinc-100/80 group transition ease-in-out duration-200 dark:border-zinc-600/80 dark:focus:ring-zinc-600/30 dark:focus:border-zinc-600 dark:shadow-zinc-950/30 dark:bg-zinc-800/90" do %>
      <div class="w-10 h-10 rounded-full border border-secondary-300/80 flex items-center justify-center bg-white flex-shrink-0 group-hover:bg-secondary-50/50 transition ease-in-out duration-200 dark:bg-zinc-800/90 dark:group-hover:bg-secondary-600/20 dark:border-secondary-600/80">
        <%= icon "user-group", classes: "w-6 h-6 flex-shrink-0 text-secondary-500" %>
      </div>
      <div>
        <h5 class="text-base font-medium font-heading text-zinc-700 dark:text-zinc-100 tracking-tight">Join the forum</h5>
        <p class="text-sm text-zinc-500 dark:text-zinc-400">Network with fellow hosts.</p>
      </div>
    <% end %>

    <%= link_to (defined?(admin_help_center_path) ? admin_help_center_path : "#"), class: "border border-zinc-300/80 shadow-sm shadow-zinc-300/25 hover:shadow flex items-center rounded-lg px-4 py-5 space-x-3 focus:ring-4 focus:ring-zinc-100/80 group transition ease-in-out duration-200 dark:bg-zinc-800/90 dark:border-zinc-600/80 dark:focus:ring-zinc-600/30 dark:focus:border-zinc-600 dark:shadow-zinc-950/30" do %>
      <div class="w-10 h-10 rounded-full border border-zinc-400/80 flex items-center justify-center bg-white flex-shrink-0 transition ease-in-out duration-200 group-hover:bg-zinc-50/80 dark:bg-zinc-800/90 dark:group-hover:bg-zinc-700/70">
        <%= icon "tv", classes: "text-zinc-500 w-6 h-6 flex-shrink-0 dark:group-hover:text-zinc-400" %>
      </div>
      <div>
        <h5 class="text-base font-medium font-heading text-zinc-700 dark:text-zinc-100 tracking-tight">Watch tutorials</h5>
        <p class="text-sm text-zinc-500 dark:text-zinc-400">Watch video tutorials to learn.</p>
      </div>
    <% end %>

    <%= link_to (defined?(admin_help_center_path) ? admin_help_center_path : "#"), class: "border border-zinc-300/80 shadow-sm shadow-zinc-300/25 hover:shadow flex items-center rounded-lg px-4 py-5 space-x-3 focus:ring-4 focus:ring-zinc-100/80 transition ease-in-out duration-200 group dark:bg-zinc-800/90 dark:border-zinc-600/80 dark:focus:ring-zinc-600/30 dark:focus:border-zinc-600 dark:shadow-zinc-950/30" do %>
       <div class="w-10 h-10 rounded-full border border-violet-500/80 dark:border-violet-600/70 flex items-center justify-center bg-white flex-shrink-0 transition ease-in-out duration-200 group-hover:bg-violet-50/50 dark:bg-zinc-800/90 dark:group-hover:bg-violet-600/20">
        <%= icon "queue-list", classes: "text-violet-500 dark:group-hover:text-violet-400/80 w-6 h-6 flex-shrink-0" %>
      </div>
      <div>
        <h5 class="text-base font-medium font-heading text-zinc-700 dark:text-zinc-100 tracking-tight">Product updates</h5>
        <p class="text-sm text-zinc-500 dark:text-zinc-400">Read about upcoming changes.</p>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="container mx-auto px-4 pb-10 font-heading">
  <div class="grid md:grid-cols-4 grid-cols-2 gap-6">
    <div>
      <h4 class="text-zinc-800 text-lg font-medium mb-4 dark:text-zinc-50">Support</h4>
      <ul class="leading-[2.8rem] text-zinc-500/90 dark:text-zinc-400/90">

        <li>
          <%= link_to "Get help", (defined?(admin_help_center_path) ? admin_help_center_path : "#"), class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>

        <li>
          <a href="#" class="hover:text-zinc-700 dark:hover:text-zinc-300/90">Forum</a>
        </li>

        <li>
          <%= link_to "Documentation", (defined?(admin_help_center_path) ? admin_help_center_path : "#"), class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>

        <li>
          <a href="#" class="hover:text-zinc-700 dark:hover:text-zinc-300/90">Tutorials</a>
        </li>

        <li>
          <%= link_to "Product updates", (defined?(admin_changelog_path) ? admin_changelog_path : "#"), class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>

        <li>
          <%= link_to "Give feedback", (defined?(admin_contact_path) ? admin_contact_path : "#"), class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>
      </ul>
    </div>
    <div>
      <h4 class="text-zinc-800 text-lg font-medium mb-4 dark:text-zinc-50">Hosting</h4>
      <ul class="leading-[2.8rem] text-zinc-500/90 dark:text-zinc-400/90">

        <li>
          <%= link_to "Pricing", (defined?(pricing_path) ? pricing_path : "#"), class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>

        <li>
          <%= link_to "Resources", (defined?(admin_help_center_path) ? admin_help_center_path : "#"), class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>
        <li>
          <%= link_to "Affiliates", "#", class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>
        <li>
          <%= link_to "Integrations", "#", class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>

        <li>
          <%= link_to "API Access", (defined?(admin_api_path) ? admin_api_path : "#"), class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>

        <li>
          <a href="#" class="hover:text-zinc-700 dark:hover:text-zinc-300/90">Booking direct</a>
        </li>
      </ul>
    </div>
    <div>
      <h4 class="text-zinc-800 text-lg font-medium mb-4 dark:text-zinc-50">Company</h4>
      <ul class="leading-[2.8rem] text-zinc-500/90 dark:text-zinc-400/90">

        <li>
          <%= link_to "About us", (defined?(about_path) ? about_path : "#"), class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>

        <li>
          <a href="#" class="hover:text-zinc-700 dark:hover:text-zinc-300/90">Careers</a>
        </li>
        <li>
          <a href="#" class="hover:text-zinc-700 dark:hover:text-zinc-300/90">Blog</a>
        </li>

        <li>
          <%= link_to "Contact us", (defined?(admin_contact_path) ? admin_contact_path : "#"), class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>
      </ul>
    </div>
    <div></div>
  </div>

  <div
    class="md:flex items-center pt-6 mt-16 border-t border-zinc-300/50 dark:border-zinc-600/50 flex-wrap md:justify-start justify-center">
    <div class="md:flex-1 md:flex items-center">
      <%= link_to root_path, class: "flex items-center md:space-x-3 justify-center md:justify-start group" do %>
        <svg class="fill-current text-zinc-900 dark:text-zinc-100 dark:group-hover:text-white" width="36" height="36"
          viewBox="0 0 36 36" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" clip-rule="evenodd"
            d="M30 0C33.3137 0 36 2.68629 36 6V30C36 33.3137 33.3137 36 30 36H6C2.68629 36 0 33.3137 0 30V6C0 2.68629 2.68629 0 6 0H30ZM16.1275 30.7111C16.3442 30.7438 16.5195 30.5309 16.5195 30.3117V25.6407C16.5195 23.3795 14.0716 21.9662 12.1133 23.0968C11.4052 23.5057 10.4997 23.2631 10.0909 22.5549C9.68208 21.8468 9.9247 20.9413 10.6328 20.5325C12.6123 19.3896 12.6123 16.5325 10.6328 15.3896C9.9247 14.9808 9.68208 14.0753 10.0909 13.3672C10.4997 12.6591 11.4052 12.4165 12.1133 12.8253C14.0716 13.9559 16.5195 12.5426 16.5195 10.2814V9.1364C16.5195 6.97891 14.5901 5.27606 12.6335 6.1852C8.20999 8.24062 5.14286 12.7232 5.14286 17.9221C5.14286 24.403 9.90907 29.7706 16.1275 30.7111ZM31.013 17.9221C31.013 24.4524 26.1737 29.8525 19.8856 30.7318C19.6601 30.7634 19.4805 30.5395 19.4805 30.3117V25.5541C19.4805 23.3069 21.9132 21.9024 23.8594 23.026C24.5675 23.4348 25.473 23.1922 25.8818 22.4841C26.2907 21.776 26.048 20.8705 25.3399 20.4617C23.415 19.3503 23.415 16.5718 25.3399 15.4605C26.048 15.0516 26.2907 14.1462 25.8818 13.438C25.473 12.7299 24.5675 12.4873 23.8594 12.8961C21.9132 14.0198 19.4805 12.6152 19.4805 10.368V9.11727C19.4805 6.95171 21.4035 5.2311 23.3785 6.11944C27.8792 8.14385 31.013 12.667 31.013 17.9221Z" />
        </svg>

        <span
          class="font-semibold text-xl lg:block hidden dark:text-zinc-100 dark:group-hover:text-white">Shepherd</span>
      <% end %>

      <ul
        class="md:flex md:w-auto w-full items-center md:space-x-4 font-light md:ml-4 text-zinc-500 md:text-left text-center md:leading-normal leading-loose my-5 md:my-0 md:text-base text-sm dark:text-zinc-500">
        <li>&copy; 2023, Shepherd Inc.</li>

        <li>
          <%= link_to "Terms", (defined?(admin_terms_path) ? admin_terms_path : "#"), class: "hover:text-zinc-800 dark:hover:text-zinc-400" %>
        </li>

        <li>
          <%= link_to "Privacy", (defined?(admin_privacy_path) ? admin_privacy_path : "#"), class: "hover:text-zinc-800 dark:hover:text-zinc-400" %>
        </li>
      </ul>
    </div>

    <ul class="flex justify-center items-center space-x-8">
      <li>
        <%= link_to "#", class: "group" do %>
          <%= icon "instagram.svg", path: "social/instagram.svg", classes: "w-6 h-6 fill-current text-zinc-700 dark:text-zinc-600 dark:group-hover:text-white group-hover:text-zinc-800" %>
        <% end %>
      </li>

      <li>
        <%= link_to "#", class: "group" do %>
          <%= icon "x.svg", path: "social/x.svg", classes: "w-6 h-6 fill-current text-zinc-700 dark:text-zinc-600 dark:group-hover:text-white group-hover:text-zinc-800" %>
        <% end %>
      </li>

      <li>
        <%= link_to "#", class: "group" do %>
          <%= icon "facebook", path: "social/facebook.svg", classes: "w-6 h-6 fill-current text-zinc-700 dark:text-zinc-600 dark:group-hover:text-white group-hover:text-zinc-800" %>
        <% end %>
      </li>

      <li>
        <%= link_to "#", class: "group" do %>
          <%= icon "linkedin", path: "social/linkedin.svg", classes: "w-6 h-6 fill-current text-zinc-700 dark:text-zinc-600 dark:group-hover:text-white group-hover:text-zinc-800" %>
        <% end %>
      </li>

      <li>
        <%= link_to "#", class: "group" do %>
          <%= icon "youtube", path: "social/youtube.svg", classes: "w-6 h-6 fill-current text-zinc-700 dark:text-zinc-600 dark:group-hover:text-white group-hover:text-zinc-800" %>
        <% end %>
      </li>
    </ul>
  </div>
</footer>